// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StyledHelloModuleScssNamespace {
  export interface IStyledHelloModuleScss {
    greeting: string;
  }
}

declare const StyledHelloModuleScssModule: StyledHelloModuleScssNamespace.IStyledHelloModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StyledHelloModuleScssNamespace.IStyledHelloModuleScss;
};

export = StyledHelloModuleScssModule;
