// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SrcIndexScssNamespace {
  export interface ISrcIndexScss {
    "main-container": string;
  }
}

declare const SrcIndexScssModule: SrcIndexScssNamespace.ISrcIndexScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SrcIndexScssNamespace.ISrcIndexScss;
};

export = SrcIndexScssModule;
